
SELECT * from usuario as U
inner join usuario_formacao as UF
on U.ID_USUARIO = UF.ID_USUARIO
INNER JOIN FORMACAO AS F
ON F.ID_FORMACAO = UF.ID_FORMACAO
INNER JOIN USUARIO_EXPERIENCIA AS UE
ON UE.ID_USUARIO = U.ID_USUARIO
INNER JOIN EXPERIENCIA AS E
ON E.ID_EXPERIENCIA = UE.ID_EXPERIENCIA
INNER JOIN USUARIO_ESCOLARIDADE AS UES
ON UES.ID_USUARIO = U.ID_USUARIO
INNER JOIN ESCOLARIDADE AS ES
ON ES.ID_ESCOLARIDADE = UES.ID_ESCOLARIDADE
INNER JOIN USUARIO_CURSO_EXTRA AS UCX
ON UCX.ID_USUARIO = U.ID_USUARIO
INNER JOIN CURSO_EXTRA AS CX
ON CX.ID_CURSO = UCX.ID_CURSO_EXTRA


CREATE TABLE `curso_extra` (
 `ID_CURSO` int NOT NULL AUTO_INCREMENT,
 `NOME` varchar(45) DEFAULT NULL,
 `INSTITUICAO` varchar(45) DEFAULT NULL,
 `STATUS` varchar(45) DEFAULT NULL,
 `DURACAO` varchar(45) DEFAULT NULL,
 `NIVEL_TECNICO` varchar(45) DEFAULT NULL,
 `ID_USUARIO` int DEFAULT NULL,
 PRIMARY KEY (`ID_CURSO`),
 KEY `ID_USUARIO_idx` (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


	CREATE TABLE `escolaridade` (
 `ID_ESCOLARIDADE` int NOT NULL AUTO_INCREMENT,
 `CURSO` varchar(45) NOT NULL,
 `INSTITUICAO` varchar(45) NOT NULL,
 `CONTATO` varchar(45) NOT NULL,
 `TURNO` varchar(45) NOT NULL,
 `PREVISAO_FORMATURA` date NOT NULL,
 `PERIODO` int NOT NULL,
 `DURACAO` int NOT NULL,
 `DECLARACAO_MATRICULA` blob NOT NULL,
 `ID_USUARIO` int NOT NULL,
 PRIMARY KEY (`ID_ESCOLARIDADE`),
 KEY `ID_USUSARIO_idx` (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


	CREATE TABLE `experiencia` (
 `ID_EXPERIENCIA` int NOT NULL AUTO_INCREMENT,
 `EMPRESA` varchar(45) DEFAULT NULL,
 `CARGO` varchar(45) DEFAULT NULL,
 `INICIO` date DEFAULT NULL,
 `FIM` date DEFAULT NULL,
 `TIPO_CONTRATO` varchar(45) DEFAULT NULL,
 `ATIVIDADES` varchar(300) DEFAULT NULL,
 `ID_USUARIO` int DEFAULT NULL,
 PRIMARY KEY (`ID_EXPERIENCIA`),
 KEY `ID_USUSARIO_idx` (`ID_USUARIO`),
 CONSTRAINT `ID_USUSARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuario` (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


	CREATE TABLE `formacao` (
 `ID_FORMACAO` int NOT NULL AUTO_INCREMENT,
 `CURSO` varchar(45) NOT NULL,
 `INSTITUICAO` varchar(45) NOT NULL,
 `NIVEL` varchar(45) NOT NULL,
 `DURACAO` int NOT NULL,
 `STATUS` varchar(45) NOT NULL,
 `ID_USUARIO` int NOT NULL,
 PRIMARY KEY (`ID_FORMACAO`),
 KEY `ID_USUARIO_idx` (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


	CREATE TABLE `usuario` (
 `ID_USUARIO` int NOT NULL AUTO_INCREMENT,
 `NOME` varchar(45) NOT NULL,
 `EMAIL` varchar(50) NOT NULL,
 `CPF` int NOT NULL,
 `DATA_NASC` date NOT NULL,
 `IDADE` int NOT NULL,
 `NOME_MAE` varchar(45) NOT NULL,
 `NOME_PAI` varchar(45) DEFAULT NULL,
 `RG` int NOT NULL,
 `DATA_EMISSAO` date NOT NULL,
 `ORGAO_EMISSOR` varchar(45) NOT NULL,
 `ESTADO` varchar(45) NOT NULL,
 `SENHA` varchar(50) NOT NULL,
 `login` varchar(45) NOT NULL,
 PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci